@startuml

together {
        class Jugador
        class Ficha
}

class Juego {
        + haGanado(j : Jugador) : Boolean
}

class Tablero {
        + haCompletadoLinea(j : Jugador) : Boolean
}

class Linea3 {
        + todasLasFichasSonDe(j : Jugador) : Boolean
}

class Jugador {
        + miFicha() : Ficha
}

class Ficha {
        - caracter : Chart
        
        + igualA(otra : Ficha) : Boolean
}

class Celda {
        - contenido : Ficha
        + contiene(f : Ficha) : Boolean
}

Juego o-left- "2" Jugador
Juego *-right- "1" Tablero
Tablero *-- "8" Linea3 
Jugador o- "*" Ficha
Linea3 "3" o- Celda
Celda o- "0..1" Ficha

@enduml
